apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oxb08xtej-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oxb08xtej-nodejs 
  name: oxb08xtej-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oxb08xtej-nodejs 
